---
title: "SVMmodel"
author: "Mia Gale"
format: html
editor: visual
---

## SVM Model

```{r}
#| message: false
#| warning: false

library(tidymodels)   # Core framework for modeling (includes recipes, workflows, parsnip, etc.)
library(finetune)     # Additional tuning strategies (e.g., racing, ANOVA-based tuning)
library(vip)          # For plotting variable importance from fitted models
library(ranger)       # Fast implementation of Random Forests
library(tidyverse)    # Data wrangling and visualization
library(doParallel)   # For parallel computing (useful during resampling/tuning)
library(caret)       # Other great library for Machine Learning 
library(kernlab)      # SVM engine used by tidymodels
library(here)

```

```{r}

corn_training_reduced <- read.csv(here("data", "corn_training_reduced.csv"))

set.seed(9678965) # Setting seed to get reproducible results 

corn_split_svm <- initial_split(corn_training_reduced,
                            prop = .7,                 # proportion of split same as previous codes
                            strata = yield_mg_ha) 
  
corn_split_svm
```

```{r}

corn_train_svm <- training(corn_split_svm)  # 70% of data

corn_train_svm #This is your training data frame

```

```{r}
corn_test_svm <- testing(corn_split_svm)

corn_test_svm

```

```{r}


ggplot() +
  geom_density(data = corn_train_svm, 
               aes(x = yield_mg_ha),
               color = "red") +
  geom_density(data = corn_test_svm, 
               aes(x = yield_mg_ha),
               color = "blue") 


```

```{r}

# Create recipe for data preprocessing
corn_recipe_svm <- recipe(yield_mg_ha ~ ., data = corn_train_svm) %>%
  step_impute_median(all_numeric_predictors()) %>%             #changing NAs values to median values
  step_normalize(all_numeric_predictors()) %>%                 #We should normalize our variables for SVM
  step_zv(all_predictors())                                    #removing zero variance

corn_recipe_svm

```

```{r}
# Prep the recipe to estimate any required statistics
corn_prep_svm <- corn_recipe_svm %>% 
  prep()

# Examine preprocessing steps
corn_prep_svm

```

```{r}

svm_spec <- # Specifying SVM as our model type, asking to tune the hyperparameters
  svm_rbf(                 # Most common choice for nonlinear regression
    cost = tune(),        # Controls model complexity
    rbf_sigma = tune()    # Controls the smoothness of the radial kernel
  ) %>%
  # specify engine
  set_engine("kernlab") %>%
  # Set to mode
  set_mode("regression")

svm_spec

```

```{r}

set.seed(657) #34549

resampling_foldcv <- vfold_cv(corn_train_svm, # Create 10-fold cross-validation resampling object from training data
                              v = 10)

resampling_foldcv
resampling_foldcv$splits[[1]]

```

```{r}

svm_grid <- grid_latin_hypercube(
  cost(),
  rbf_sigma(),
  size = 100
)

svm_grid

```

```{r}

ggplot(data = svm_grid,
       aes(x = cost, 
           y = rbf_sigma)) +
  geom_point(alpha = .5)


```

```{r}

set.seed(6576)
registerDoParallel(cores = parallel::detectCores() - 1)

svm_res <- tune_race_anova(
  object = svm_spec,
  preprocessor = corn_recipe_svm,
  resamples = resampling_foldcv,
  grid = svm_grid,
  control = control_race(save_pred = TRUE)
)

stopImplicitCluster()

beepr::beep()
svm_res$.metrics[[1]]

```

```{r}

plot_race(svm_res)

```

```{r}

# Based on lowest RMSE
best_rmse_svm <- svm_res %>% 
  select_best(metric = "rmse") %>% 
  mutate(source = "best_rmse")

best_rmse_svm

```

```{r}

best_rmse_pct_loss_svm <- svm_res %>% 
  select_by_pct_loss(
    cost,
    metric = "rmse",
    limit = 1
  ) %>% 
  mutate(source = "best_rmse_pct_loss")

best_rmse_pct_loss_svm

```

```{r}

# Based on lowest RMSE within 1 se
best_rmse_one_std_err_svm <- svm_res %>% 
  select_by_one_std_err(
    metric = "rmse",
    cost
  ) %>% 
  mutate(source = "best_rmse_one_std_err")

best_rmse_one_std_err_svm

```

```{r}

# Based on greatest R2
best_r2_svm <- svm_res %>% 
  select_best(metric = "rsq") %>% 
  mutate(source = "best_r2")

best_r2_svm

```

```{r}

# Based on greatest R2 within 1% loss
best_r2_pct_loss_svm <- svm_res %>% 
  select_by_pct_loss(
    cost,
    metric = "rsq",
    limit = 1
  ) %>% 
  mutate(source = "best_r2_pct_loss")

best_r2_pct_loss_svm

```

```{r}

# Based on lowest R2 within 1 se
best_r2_one_std_error_svm <- svm_res %>% 
  select_by_one_std_err(
    metric = "rsq",
    cost
  ) %>%
  mutate(source = "best_r2_one_std_error")

best_r2_one_std_error_svm

```

```{r}

best_rmse_svm %>% 
  bind_rows(
    best_rmse_pct_loss_svm, 
    best_rmse_one_std_err_svm, 
    best_r2_svm, 
    best_r2_pct_loss_svm, 
    best_r2_one_std_error_svm
  )

```

```{r}

final_spec_svm <- svm_rbf(
  cost = best_rmse_svm$cost,               # Cost parameter
  rbf_sigma = best_rmse_svm$rbf_sigma      # Radial basis kernel parameter
) %>%
  set_engine("kernlab") %>%
  set_mode("regression")

final_spec_svm

```

```{r}

set.seed(877)

  final_fit_svm <- last_fit(final_spec_svm,
                            corn_recipe_svm,
                            split = corn_split_svm)

final_fit_svm %>%
  collect_predictions()

```

```{r}

   final_fit_svm %>%
     collect_metrics()

```

```{r}
   
final_spec_svm %>%
  fit(yield_mg_ha ~ .,
      data = bake(corn_prep_svm, 
                  corn_train_svm)) %>%
  augment(new_data = bake(corn_prep_svm, 
                          corn_train_svm)) %>% 
  rmse(yield_mg_ha, .pred) %>%
  bind_rows(
    
    # R2
    final_spec_svm %>%
      fit(yield_mg_ha ~ .,
          data = bake(corn_prep_svm, 
                      corn_train_svm)) %>%
      augment(new_data = bake(corn_prep_svm, 
                              corn_train_svm)) %>% 
      rsq(yield_mg_ha, .pred))

```

```{r}

collect_predictions(final_fit_svm) %>%
  ggplot(aes(x = yield_mg_ha, y = .pred)) +
  geom_point(alpha = 0.5) +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  labs(
    x = "Observed Yield",
    y = "Predicted Yield",
    title = "Observed vs Predicted Yield - SVM"
  ) +
  theme_minimal()

```

```{r}

library(vip)

svm_fit <- final_spec_svm %>%
  fit(
    yield_mg_ha ~ .,
    data = bake(corn_prep_svm, corn_train_svm)
  )

train_baked_svm <- bake(corn_prep_svm, corn_train_svm)

vip::vi_permute(
  object = svm_fit,
  train = train_baked,
  target = "yield_mg_ha",
  metric = "rmse",
  pred_wrapper = function(object, newdata) {
    predict(object, newdata)$.pred
  },
  nsim = 10)

```
